### PR TITLE
[#136243763] Notify users about OOM killed processes

### PR DESCRIPTION
**Pull request by Jonty**
This is a quick sketch of a fix for [#136243763](https://www.pivotaltracker.com/n/projects/1003146/stories/136243763), however I am unsure that this is the correct approach to be taking.

Happy to iterate on the code if it's worth it, however if you feel that the approach is completely wrong I'm also happy to close this PR.

### CODE REVIEW

**Comment by ematpl** [comment]
Thanks, @Jonty. I don't think polling on each individual RunAction is the best strategy, as a container could have multiple long-lived RunActions (and in fact in practice SSH-enabled CF apps have both the app start command and an SSH server running). Garden's API does currently require us to poll for these events, but that polling would make more sense at the container level, perhaps somewhere in the executor's [ContainerStore](https://github.com/cloudfoundry/executor/blob/master/depot/containerstore/containerstore.go).

Also, I think garden-runc might be able only to notify the client that an OOM event happened, and not provide the PID that was killed, at least based on the minimal amount of information coming from `runc events`: https://github.com/opencontainers/runc/blob/master/events.go#L172. So even if we detect that an out-of-memory event occurred, there unfortunately isn't much specific information to convey.

**Comment by Jonty** [comment]
@ematpl Aha, I didn't realise that multiple RunActions were possible in a given cgroup. I'll see if I can rewrite this to live in ContainerStore or somewhere similar - would that be acceptable?

Unfortunately the kernel interface for OOM events can only tell you that one has occurred. However it would be possible to subscribe to [systemtap events](http://serverfault.com/a/382342) in order to log PID & process name, or take the cAdvisor approach and [parse syslog](https://github.com/google/cadvisor/blob/master/utils/oomparser/oomparser.go) for the logged events - for the latter solution you'd also need to track PIDs in each cgroup to ensure you surface the events in the correct app log.

While the above solutions would give substantially more information, the current issue is that OOM events in containers are not surfaced to users _at all_. When they're occurring the user will have no idea why forked processes in their container are going missing, and they will have no choice but to contact the CF operator for debugging help.

**Comment by ematpl** [comment]
@Jonty Sure, I think we'd take something at the ContainerStore level.

I'd like to get more process information in the OOM events, but those OS-specific details should likely be extracted at the runc or guardian/garden-runc level. @julz may have some thoughts on where that would be most appropriate.

Best,
Eric

**Comment by heyjcollins** [comment]
As this item has been open for quite a long time, I'm going to go ahead and close it.

**Pull request closed without merging**
